### ISSUE TITLE
Setup.py fails when installing via pip

### ISSUE THREAD

**Issue by pietdevaere** [abertschi/postcards#37]
```
# pip3 install postcards
Collecting postcards
  Using cached postcards-1.1.tar.gz (44 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-9mg99o9f/postcards/setup.py'"'"'; __file__='"'"'/tmp/pip-install-9mg99o9f/postcards/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-b12p5w57
         cwd: /tmp/pip-install-9mg99o9f/postcards/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-9mg99o9f/postcards/setup.py", line 14, in <module>
        reqs = [str(ir.req) for ir in install_reqs]
      File "/tmp/pip-install-9mg99o9f/postcards/setup.py", line 14, in <listcomp>
        reqs = [str(ir.req) for ir in install_reqs]
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by pietdevaere** [comment]
Issue seems to be with recent changes to the pip api. See also https://github.com/pypa/pip/issues/8188

**Comment by spameier** [comment]
Could you release a new version to PyPi, as `pip install postcards` does not currently work?

**Comment by abertschi** [comment]
Yes, it's on my to do list. But will not get to it before mid February. I'm sorry.
In the meantime you could wire up the unreleased dependencies yourself. Or wait until then.
I already fixed the endpoint wrappers and tested them. The current state is here https://github.com/abertschi/postcard_creator_wrapper/tree/develop
