### ISSUE TITLE
Can't pip install the package

### ISSUE THREAD

**Issue by SBBBEGRUSSTSIE** [abertschi/postcards#66]
Hey, 

I've been trying to pip install but there is something that won't download. It seems like I need to use another version of cython or something.
Here's the code : 
`Collecting PyYAML==6.0 (from postcards)
  Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib\PyYAML.egg-info\PKG-INFO
      writing dependency_links to lib\PyYAML.egg-info\dependency_links.txt
      writing top-level names to lib\PyYAML.egg-info\top_level.txt
      Traceback (most recent call last):
        File "C:\Users\sdalh\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\sdalh\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\sdalh\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\sdalh\AppData\Local\Temp\pip-build-env-6j0d0nlv\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\sdalh\AppData\Local\Temp\pip-build-env-6j0d0nlv\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\sdalh\AppData\Local\Temp\pip-build-env-6j0d0nlv\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
        File "C:\Users\sdalh\AppData\Local\Temp\pip-build-env-6j0d0nlv\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\sdalh\AppData\Local\Temp\pip-build-env-6j0d0nlv\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\sdalh\AppData\Local\Temp\pip-build-env-6j0d0nlv\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\sdalh\AppData\Local\Temp\pip-build-env-6j0d0nlv\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\sdalh\AppData\Local\Temp\pip-build-env-6j0d0nlv\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\sdalh\AppData\Local\Temp\pip-build-env-6j0d0nlv\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\sdalh\AppData\Local\Temp\pip-build-env-6j0d0nlv\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 318, in run
          self.find_sources()
        File "C:\Users\sdalh\AppData\Local\Temp\pip-build-env-6j0d0nlv\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 326, in find_sources
          mm.run()
        File "C:\Users\sdalh\AppData\Local\Temp\pip-build-env-6j0d0nlv\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 548, in run
          self.add_defaults()
        File "C:\Users\sdalh\AppData\Local\Temp\pip-build-env-6j0d0nlv\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 586, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\sdalh\AppData\Local\Temp\pip-build-env-6j0d0nlv\overlay\Lib\site-packages\setuptools\command\sdist.py", line 113, in add_defaults
          super().add_defaults()
        File "C:\Users\sdalh\AppData\Local\Temp\pip-build-env-6j0d0nlv\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "C:\Users\sdalh\AppData\Local\Temp\pip-build-env-6j0d0nlv\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 204, in get_source_files
        File "C:\Users\sdalh\AppData\Local\Temp\pip-build-env-6j0d0nlv\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.`

I've heard of that superb idea (I'm talking about the code) from a friend of mine, so I decided to try to implement it to my computer. Problem is I'm quite a noob with coding, so I'm trying as hard as I can to understand something at this, but I'll need some patient explanation to achieve this. Thank you very much for your work !

**Comment by abertschi** [comment]
I dont know how well the Windows support is for the dependencies of this project. You may want to try to install this in a virtual environment in the Windows Subsystem for Linux or on a Linux machine altogether.

**Comment by dalhei-lama** [comment]
Okay, thank for the quick response, I tried your solution but finally ended up installing an older Python version, as it apparently solved the problem.
